package aces.webctrl.wireshark.broadcast;
import java.nio.charset.*;
/**
 * Encapsulated various lists of data specific to the BACnet protocol.
 */
public class Constants {
  /**
   * @return the name for the BACnet service with the given ID, or {@code "UNKNOWN"} if the service cannot be found.
   */
  public static String getService(int ID){
    if (ID>=0){
      return ID<services.length?services[ID]:"UNKNOWN";
    }
    ID = -ID-1;
    if (ID<networkMessageTypes.length){
      return networkMessageTypes[ID];
    }
    if (ID<128){
      return "Reserved by ASHRAE";
    }
    if (ID<256){
      return "Vendor Proprietary Message";
    }
    return "UNKNOWN";
  }
  /**
   * @return the vendor with the given ID, or {@code "UNKNOWN"} if the vendor cannot be found.
   */
  public static String getVendor(int ID){
    if (ID<0 || ID>=vendors.length){
      return "UNKNOWN";
    }
    return vendors[ID];
  }
  /**
   * @return the object type with the given code, or {@code "unknown"} if the object type cannot be identified.
   */
  public static String getObjectType(int code){
    if (code>=0 && code<objectTypes.length){
      return objectTypes[code];
    }else{
      return "unknown";
    }
  }
  /**
   * @return the charset with the the given ID.
   */
  public static Charset getCharset(int ID){
    if (ID>=0 && ID<charsets.length){
      return charsets[ID];
    }else{
      return StandardCharsets.UTF_8;
    }
  }
  /**
   * @return a Charset with the given name. Defaults to UTF_8 if no charset can be found.
   */
  private static Charset get(String name){
    try{
      return Charset.forName(name);
    }catch(Throwable t){
      return StandardCharsets.UTF_8;
    }
  }
  /**
   * A list of character sets which may be used for String encoding in the BACnet protocol.
   */
  public final static Charset[] charsets = new Charset[]{
    StandardCharsets.UTF_8,
    get("IBM850"),
    get("EUC-JP"),
    get("UTF-32"),
    StandardCharsets.UTF_16,
    StandardCharsets.ISO_8859_1
  };
  /**
   * A list of valid object types.
   */
  public final static String[] objectTypes = new String[]{
    "analog-input",
    "analog-output",
    "analog-value",
    "binary-input",
    "binary-output",
    "binary-value",
    "calendar",
    "command",
    "device",
    "event-enrollment",
    "file",
    "group",
    "loop",
    "multi-state-input",
    "multi-state-output",
    "notification-class",
    "program",
    "schedule",
    "averaging",
    "multi-state-value",
    "trend-log",
    "life-safety-point",
    "life-safety-zone",
    "accumulator",
    "pulse-converter",
    "event-log",
    "global-group",
    "trend-log-multiple",
    "load-control",
    "structured-view",
    "access-door",
    "timer",
    "access-credential",
    "access-point",
    "access-rights",
    "access-user",
    "access-zone",
    "credential-data-input",
    "unknown",
    "bitstring-value",
    "characterstring-value",
    "datepattern-value",
    "date-value",
    "datetimepattern-value",
    "datetime-value",
    "integer-value",
    "large-analog-value",
    "octetstring-value",
    "positive-integer-value",
    "timepattern-value",
    "time-value",
    "notification-forwarder",
    "alert-enrollment",
    "channel",
    "lighting-output",
    "binary-lighting-output",
    "network-port",
    "elevator-group",
    "escalator",
    "lift",
    "staging",
    "audit-log",
    "audit-reporter"
  };
  /**
   * A list of typical BACnet broadcast services.
   */
  public final static String[] services = new String[]{
    "i-Am",
    "i-Have",
    "unconfirmedCOVNotification",
    "unconfirmedEventNotification",
    "unconfirmedPrivateTransfer",
    "unconfirmedTextMessage",
    "timeSynchronization",
    "who-Has",
    "who-Is",
    "utcTimeSynchronization",
    "writeGroup",
    "unconfirmedCovNotificationMultiple",
    "unconfirmedAuditNotification",
    "who-am-I",
    "you-are"
  };
  /**
   * A list of BACnet broadcast types sent as network-layer messages.
   */
  public final static String[] networkMessageTypes = new String[]{
    "Who-Is-Router-To-Network",
    "I-Am-Router-To-Network",
    "I-Could-Be-Router-To-Network",
    "Reject-Message-To-Network",
    "Router-Busy-To-Network",
    "Router-Available-To-Network",
    "Initialize-Routing-Table",
    "Initialize-Routing-Table-Ack",
    "Establish-Connection-To-Network",
    "Disconnect-Connection-To-Network",
    "Challenge-Request",
    "Security-Payload",
    "Security-Response",
    "Request-Key-Update",
    "Update-Keyset",
    "Update-distribution-Key",
    "Request-Masterkey",
    "Set-Masterkey",
    "What-Is-Networknumber",
    "Networknumber-Is"
  };
  /**
   * A list of BACnet vendor IDs assigned by ASHRAE.
   * https://bacnet.org/assigned-vendor-ids/
   */
  public final static String[] vendors = new String[]{
    "ASHRAE",
    "NIST",
    "The Trane Company",
    "Daikin Applied Americas",
    "PolarSoft",
    "Johnson Controls, Inc.",
    "ABB (Formerly American Auto-Matrix)",
    "Siemens Schweiz AG (Formerly: Landis & Staefa Division Europe)",
    "Delta Controls",
    "Siemens Schweiz AG",
    "Schneider Electric",
    "TAC",
    "Orion Analysis Corporation",
    "Teletrol Systems Inc.",
    "Cimetrics Technology",
    "Cornell University",
    "United Technologies Carrier",
    "Honeywell Inc.",
    "Alerton / Honeywell",
    "TAC AB",
    "Hewlett-Packard Company",
    "Dorsette’s Inc.",
    "Siemens Schweiz AG (Formerly: Cerberus AG)",
    "York Controls Group",
    "Automated Logic Corporation",
    "CSI Control Systems International",
    "Phoenix Controls Corporation",
    "Innovex Technologies, Inc.",
    "KMC Controls, Inc.",
    "Xn Technologies, Inc.",
    "Hyundai Information Technology Co., Ltd.",
    "Tokimec Inc.",
    "Simplex",
    "North Building Technologies Limited",
    "Notifier",
    "Reliable Controls Corporation",
    "Tridium Inc.",
    "MSA Safety",
    "Silicon Energy",
    "Kieback & Peter GmbH & Co KG",
    "Anacon Systems, Inc.",
    "Systems Controls & Instruments, LLC",
    "Acuity Brands Lighting, Inc.",
    "Micropower Manufacturing",
    "Matrix Controls",
    "METALAIRE",
    "ESS Engineering",
    "Sphere Systems Pty Ltd.",
    "Walker Technologies Corporation",
    "H I Solutions, Inc.",
    "MBS GmbH",
    "SAMSON AG",
    "Badger Meter Inc.",
    "DAIKIN Industries Ltd.",
    "NARA Controls Inc.",
    "Mammoth Inc.",
    "Liebert Corporation",
    "SEMCO Incorporated",
    "Air Monitor Corporation",
    "TRIATEK, LLC",
    "NexLight",
    "Multistack",
    "TSI Incorporated",
    "Weather-Rite, Inc.",
    "Dunham-Bush",
    "Reliance Electric",
    "LCS Inc.",
    "Regulator Australia PTY Ltd.",
    "Touch-Plate Lighting Controls",
    "Amann GmbH",
    "RLE Technologies",
    "Cardkey Systems",
    "SECOM Co., Ltd.",
    "ABB Gebäudetechnik AG Bereich NetServ",
    "KNX Association cvba",
    "Institute of Electrical Installation Engineers of Japan (IEIEJ)",
    "Nohmi Bosai, Ltd.",
    "Carel Industries S.p.A.",
    "UTC Fire & Security España, S.L.",
    "Hochiki Corporation",
    "Fr. Sauter AG",
    "Matsushita Electric Works, Ltd.",
    "Mitsubishi Electric Corporation, Inazawa Works",
    "Mitsubishi Heavy Industries, Ltd.",
    "Xylem, Inc.",
    "Yamatake Building Systems Co., Ltd.",
    "The Watt Stopper, Inc.",
    "Aichi Tokei Denki Co., Ltd.",
    "Activation Technologies, LLC",
    "Saia-Burgess Controls, Ltd.",
    "Hitachi, Ltd.",
    "Novar Corp./Trend Control Systems Ltd.",
    "Mitsubishi Electric Lighting Corporation",
    "Argus Control Systems, Ltd.",
    "Kyuki Corporation",
    "Richards-Zeta Building Intelligence, Inc.",
    "Scientech R&D, Inc.",
    "VCI Controls, Inc.",
    "Toshiba Corporation",
    "Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works",
    "Custom Mechanical Equipment, LLC",
    "ClimateMaster",
    "ICP Panel-Tec, Inc.",
    "D-Tek Controls",
    "NEC Engineering, Ltd.",
    "PRIVA BV",
    "Meidensha Corporation",
    "JCI Systems Integration Services",
    "Freedom Corporation",
    "Neuberger Gebäudeautomation GmbH",
    "eZi Controls",
    "Leviton Manufacturing",
    "Fujitsu Limited",
    "Vertiv (Formerly Emerson Network Power)",
    "S. A. Armstrong, Ltd.",
    "Visonet AG",
    "M&M Systems, Inc.",
    "Custom Software Engineering",
    "Nittan Company, Limited",
    "Elutions Inc. (Wizcon Systems SAS)",
    "Pacom Systems Pty., Ltd.",
    "Unico, Inc.",
    "Ebtron, Inc.",
    "Scada Engine",
    "Lenze Americas (Formerly: AC Technology Corporation)",
    "Eagle Technology",
    "Data Aire, Inc.",
    "ABB, Inc.",
    "Transbit Sp. z o. o.",
    "Carrier Japan Corporation",
    "Shenzhen Junzhi Hi-Tech Co., Ltd.",
    "Tokai Soft",
    "Blue Ridge Technologies",
    "Veris Industries",
    "Centaurus Prime",
    "Sand Network Systems",
    "Regulvar, Inc.",
    "AFDtek Division of Fastek International Inc.",
    "PowerCold Comfort Air Solutions, Inc.",
    "I Controls",
    "Viconics Electronics, Inc.",
    "Yaskawa America, Inc.",
    "DEOS control systems GmbH",
    "Digitale Mess- und Steuersysteme AG",
    "Fujitsu General Limited",
    "Project Engineering S.r.l.",
    "Sanyo Electric Co., Ltd.",
    "Integrated Information Systems, Inc.",
    "Temco Controls, Ltd.",
    "Airtek International Inc.",
    "Advantech Corporation",
    "Titan Products, Ltd.",
    "Regel Partners",
    "National Environmental Product",
    "Unitec Corporation",
    "Kanden Engineering Company",
    "Messner Gebäudetechnik GmbH",
    "Integrated.CH",
    "Price Industries",
    "SE-Elektronic GmbH",
    "Rockwell Automation",
    "Enflex Corp.",
    "ASI Controls",
    "SysMik GmbH Dresden",
    "HSC Regelungstechnik GmbH",
    "Smart Temp Australia Pty. Ltd.",
    "Cooper Controls",
    "Duksan Mecasys Co., Ltd.",
    "Fuji IT Co., Ltd.",
    "Vacon Plc",
    "Leader Controls",
    "ABB (Formerly Cylon Controls, Ltd)",
    "Compas",
    "Mitsubishi Electric Building Techno-Service Co., Ltd.",
    "Building Control Integrators",
    "ITG Worldwide (M) Sdn Bhd",
    "Lutron Electronics Co., Inc.",
    "Cooper-Atkins Corporation",
    "LOYTEC Electronics GmbH",
    "ProLon",
    "Mega Controls Limited",
    "Micro Control Systems, Inc.",
    "Kiyon, Inc.",
    "Dust Networks",
    "Advanced Building Automation Systems",
    "Hermos AG",
    "CEZIM",
    "Softing",
    "Lynxspring, Inc.",
    "Schneider Toshiba Inverter Europe",
    "Danfoss Drives A/S",
    "Eaton Corporation",
    "Matyca S.A.",
    "Botech AB",
    "Noveo, Inc.",
    "AMEV",
    "Yokogawa Electric Corporation",
    "Bosch Building Automation GmbH",
    "Exact Logic",
    "Mass Electronics Pty Ltd dba Innotech Control Systems Australia",
    "Kandenko Co., Ltd.",
    "DTF, Daten-Technik Fries",
    "Klimasoft, Ltd.",
    "Toshiba Schneider Inverter Corporation",
    "Control Applications, Ltd.",
    "CIMON CO., Ltd.",
    "Onicon Incorporated",
    "Automation Displays, Inc.",
    "Control Solutions, Inc.",
    "Remsdaq Limited",
    "NTT Facilities, Inc.",
    "VIPA GmbH",
    "TSC21 Association of Japan",
    "Strato Automation",
    "HRW Limited",
    "Lighting Control & Design, Inc.",
    "Mercy Electronic and Electrical Industries",
    "Samsung SDS Co., Ltd",
    "Impact Facility Solutions, Inc.",
    "Aircuity",
    "Control Techniques, Ltd.",
    "OpenGeneral Pty., Ltd.",
    "WAGO Kontakttechnik GmbH & Co. KG",
    "Franklin Electric",
    "Chloride Power Protection Company",
    "Computrols, Inc.",
    "Phoenix Contact GmbH & Co. KG",
    "Grundfos Management A/S",
    "Ridder Drive Systems",
    "Soft Device SDN BHD",
    "Integrated Control Technology Limited",
    "AIRxpert Systems, Inc.",
    "Microtrol Limited",
    "Red Lion Controls",
    "Digital Electronics Corporation",
    "Ennovatis GmbH",
    "Serotonin Software Technologies, Inc.",
    "LS Industrial Systems Co., Ltd.",
    "Square D Company",
    "S Squared Innovations, Inc.",
    "Aricent Ltd.",
    "EtherMetrics, LLC",
    "Industrial Control Communications, Inc.",
    "Paragon Controls, Inc.",
    "A. O. Smith Corporation",
    "Contemporary Control Systems, Inc.",
    "HMS Industrial Networks SLU",
    "Ingenieurgesellschaft N. Hartleb mbH",
    "Heat-Timer Corporation",
    "Ingrasys Technology, Inc.",
    "Costerm Building Automation",
    "WILO SE",
    "Embedia Technologies Corp.",
    "Technilog",
    "HR Controls Ltd. & Co. KG",
    "Lennox International, Inc.",
    "RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG",
    "Thermomax, Ltd.",
    "ELCON Electronic Control, Ltd.",
    "Larmia Control AB",
    "BACnet Stack at SourceForge",
    "G4S Security Services A/S",
    "Exor International S.p.A.",
    "Cristal Controles",
    "Regin AB",
    "Dimension Software, Inc.",
    "SynapSense Corporation",
    "Beijing Nantree Electronic Co., Ltd.",
    "Camus Hydronics Ltd.",
    "Kawasaki Heavy Industries, Ltd.",
    "Critical Environment Technologies",
    "ILSHIN IBS Co., Ltd.",
    "ELESTA Energy Control AG",
    "KROPMAN Installatietechniek",
    "Baldor Electric Company",
    "INGA mbH",
    "GE Consumer & Industrial",
    "Functional Devices, Inc.",
    "StudioSC",
    "M-System Co., Ltd.",
    "Yokota Co., Ltd.",
    "Hitranse Technology Co., LTD",
    "Vigilent Corporation",
    "Kele, Inc.",
    "BELIMO Automation AG",
    "Gentec",
    "Embedded Science Labs, LLC",
    "Parker Hannifin Corporation",
    "MaCaPS International Limited",
    "Link4 Corporation",
    "Romutec Steuer-u. Regelsysteme GmbH",
    "Pribusin, Inc.",
    "Advantage Controls",
    "Critical Room Control",
    "LEGRAND",
    "Tongdy Control Technology Co., Ltd.",
    "ISSARO Integrierte Systemtechnik",
    "Pro-Dev Industries",
    "DRI-STEEM",
    "Creative Electronic GmbH",
    "Swegon AB",
    "FIRVENA s.r.o.",
    "Hitachi Appliances, Inc.",
    "Real Time Automation, Inc.",
    "ITEC Hankyu-Hanshin Co.",
    "Cyrus E&M Engineering Co., Ltd.",
    "Badger Meter",
    "Cirrascale Corporation",
    "Elesta GmbH Building Automation",
    "Securiton",
    "OSlsoft, Inc.",
    "Hanazeder Electronic GmbH",
    "Honeywell Security Deutschland, Novar GmbH",
    "Siemens Industry, Inc.",
    "ETM Professional Control GmbH",
    "Meitav-tec, Ltd.",
    "Janitza Electronics GmbH",
    "MKS Nordhausen",
    "De Gier Drive Systems B.V.",
    "Cypress Envirosystems",
    "SMARTron s.r.o.",
    "Verari Systems, Inc.",
    "K-W Electronic Service, Inc.",
    "ALFA-SMART Energy Management",
    "Telkonet, Inc.",
    "Securiton GmbH",
    "Cemtrex, Inc.",
    "Performance Technologies, Inc.",
    "Xtralis (Aust) Pty Ltd",
    "TROX GmbH",
    "Beijing Hysine Technology Co., Ltd",
    "RCK Controls, Inc.",
    "Distech Controls SAS",
    "Novar/Honeywell",
    "S4 Integration Solutions",
    "Schneider Electric",
    "LHA Systems",
    "GHM engineering Group, Inc.",
    "Cllimalux S.A.",
    "VAISALA Oyj",
    "COMPLEX (Beijing) Technology, Co., LTD.",
    "SCADAmetrics",
    "POWERPEG NSI Limited",
    "BACnet Interoperability Testing Services, Inc.",
    "Teco a.s.",
    "Plexus Technology, Inc.",
    "Energy Focus, Inc.",
    "Powersmiths International Corp.",
    "Nichibei Co., Ltd.",
    "HKC Technology Ltd.",
    "Ovation Networks, Inc.",
    "Setra Systems",
    "AVG Automation",
    "ZXC Ltd.",
    "Byte Sphere",
    "Generiton Co., Ltd.",
    "Holter Regelarmaturen GmbH & Co. KG",
    "Bedford Instruments, LLC",
    "Standair Inc.",
    "WEG Automation – R&D",
    "Prolon Control Systems ApS",
    "Inneasoft",
    "ConneXSoft GmbH",
    "CEAG Notlichtsysteme GmbH",
    "Distech Controls Inc.",
    "Industrial Technology Research Institute",
    "ICONICS, Inc.",
    "IQ Controls s.c.",
    "OJ Electronics A/S",
    "Rolbit Ltd.",
    "Synapsys Solutions Ltd.",
    "ACME Engineering Prod. Ltd.",
    "Zener Electric Pty, Ltd.",
    "Selectronix, Inc.",
    "Gorbet & Banerjee, LLC.",
    "IME",
    "Stephen H. Dawson Computer Service",
    "Accutrol, LLC",
    "Schneider Elektronik GmbH",
    "Alpha-Inno Tec GmbH",
    "ADMMicro, Inc.",
    "Greystone Energy Systems, Inc.",
    "CAP Technologie",
    "KeRo Systems",
    "Domat Control System s.r.o.",
    "Efektronics Pty. Ltd.",
    "Hekatron Vertriebs GmbH",
    "Securiton AG",
    "Carlo Gavazzi Controls SpA",
    "Chipkin Automation Systems",
    "Savant Systems, LLC",
    "Simmtronic Lighting Controls",
    "Abelko Innovation AB",
    "Seresco Technologies Inc.",
    "IT Watchdogs",
    "Automation Assist Japan Corp.",
    "Thermokon Sensortechnik GmbH",
    "EGauge Systems, LLC",
    "Quantum Automation (ASIA) PTE, Ltd.",
    "Toshiba Lighting & Technology Corp.",
    "SPIN Engenharia de Automação Ltda.",
    "Logistics Systems & Software Services India PVT. Ltd.",
    "Delta Controls Integration Products",
    "Focus Media",
    "LUMEnergi Inc.",
    "Kara Systems",
    "RF Code, Inc.",
    "Fatek Automation Corp.",
    "JANDA Software Company, LLC",
    "Open System Solutions Limited",
    "Intelec Systems PTY Ltd.",
    "Ecolodgix, LLC",
    "Douglas Lighting Controls",
    "iSAtech GmbH",
    "AREAL",
    "Beckhoff Automation",
    "IPAS GmbH",
    "KE2 Therm Solutions",
    "Base2Products",
    "DTL Controls, LLC",
    "INNCOM International, Inc.",
    "METZ CONNECT GmbH",
    "Greentrol Automation, Inc",
    "BELIMO Automation AG",
    "Samsung Heavy Industries Co, Ltd",
    "Triacta Power Technologies, Inc.",
    "Globestar Systems",
    "MLB Advanced Media, LP",
    "SWG Stuckmann Wirtschaftliche Gebäudesysteme GmbH",
    "SensorSwitch",
    "Multitek Power Limited",
    "Aquametro AG",
    "LG Electronics Inc.",
    "Electronic Theatre Controls, Inc.",
    "Mitsubishi Electric Corporation Nagoya Works",
    "Delta Electronics, Inc.",
    "Elma Kurtalj, Ltd.",
    "Tyco Fire & Security GmbH",
    "Nedap Security Management",
    "ESC Automation Inc.",
    "DSP4YOU Ltd.",
    "GE Sensing and Inspection Technologies",
    "Embedded Systems SIA",
    "BEFEGA GmbH",
    "Baseline Inc.",
    "Key2Act",
    "OEMCtrl",
    "Clarkson Controls Limited",
    "Rogerwell Control System Limited",
    "SCL Elements",
    "Hitachi Ltd.",
    "Newron System SA",
    "BEVECO Gebouwautomatisering BV",
    "Streamside Solutions",
    "Yellowstone Soft",
    "Oztech Intelligent Systems Pty Ltd.",
    "Novelan GmbH",
    "Flexim Americas Corporation",
    "ICP DAS Co., Ltd.",
    "CARMA Industries Inc.",
    "Log-One Ltd.",
    "TECO Electric & Machinery Co., Ltd.",
    "ConnectEx, Inc.",
    "Turbo DDC Südwest",
    "Quatrosense Environmental Ltd.",
    "Fifth Light Technology Ltd.",
    "Scientific Solutions, Ltd.",
    "Controller Area Network Solutions (M) Sdn Bhd",
    "RESOL – Elektronische Regelungen GmbH",
    "RPBUS LLC",
    "BRS Sistemas Eletronicos",
    "WindowMaster A/S",
    "Sunlux Technologies Ltd.",
    "Measurlogic",
    "Frimat GmbH",
    "Spirax Sarco",
    "Luxtron",
    "Raypak Inc",
    "Air Monitor Corporation",
    "Regler Och Webbteknik Sverige (ROWS)",
    "Intelligent Lighting Controls Inc.",
    "Sanyo Electric Industry Co., Ltd",
    "E-Mon Energy Monitoring Products",
    "Digital Control Systems",
    "ATI Airtest Technologies, Inc.",
    "SCS SA",
    "HMS Industrial Networks AB",
    "Shenzhen Universal Intellisys Co Ltd",
    "EK Intellisys Sdn Bhd",
    "SysCom",
    "Firecom, Inc.",
    "ESA Elektroschaltanlagen Grimma GmbH",
    "Kumahira Co Ltd",
    "Hotraco",
    "SABO Elektronik GmbH",
    "Equip’Trans",
    "Temperature Control Specialities Co., Inc (TCS)",
    "FlowCon International A/S",
    "ThyssenKrupp Elevator Americas",
    "Abatement Technologies",
    "Continental Control Systems, LLC",
    "WISAG Automatisierungstechnik GmbH & Co KG",
    "EasyIO",
    "EAP-Electric GmbH",
    "Hardmeier",
    "Mircom Group of Companies",
    "Quest Controls",
    "Mestek, Inc",
    "Pulse Energy",
    "Tachikawa Corporation",
    "University of Nebraska-Lincoln",
    "Redwood Systems",
    "PASStec Industrie-Elektronik GmbH",
    "NgEK, Inc.",
    "t-mac Technologies",
    "Jireh Energy Tech Co., Ltd.",
    "Enlighted Inc.",
    "El-Piast Sp. Z o.o",
    "NetxAutomation Software GmbH",
    "Invertek Drives",
    "Deutschmann Automation GmbH & Co. KG",
    "EMU Electronic AG",
    "Phaedrus Limited",
    "Sigmatek GmbH & Co KG",
    "Marlin Controls",
    "Circutor, SA",
    "UTC Fire & Security",
    "DENT Instruments, Inc.",
    "FHP Manufacturing Company – Bosch Group",
    "GE Intelligent Platforms",
    "Inner Range Pty Ltd",
    "GLAS Energy Technology",
    "MSR-Electronic-GmbH",
    "Energy Control Systems, Inc.",
    "EMT Controls",
    "Daintree",
    "EURO ICC d.o.o",
    "TE Connectivity Energy",
    "GEZE GmbH",
    "NEC Corporation",
    "Ho Cheung International Company Limited",
    "Sharp Manufacturing Systems Corporation",
    "DOT CONTROLS a.s.",
    "BeaconMedæs",
    "Midea Commercial Aircon",
    "WattMaster Controls",
    "Kamstrup A/S",
    "CA Computer Automation GmbH",
    "Laars Heating Systems Company",
    "Hitachi Systems, Ltd.",
    "Fushan AKE Electronic Engineering Co., Ltd.",
    "Toshiba International Corporation",
    "Starman Systems, LLC",
    "Samsung Techwin Co., Ltd.",
    "ISAS-Integrated Switchgear and Systems P/L",
    "Reserved for ASHRAE",
    "Obvius",
    "Marek Guzik",
    "Vortek Instruments, LLC",
    "Universal Lighting Technologies",
    "Myers Power Products, Inc.",
    "Vector Controls GmbH",
    "Crestron Electronics, Inc.",
    "A&E Controls Limited",
    "Projektomontaza A.D.",
    "Freeaire Refrigeration",
    "Aqua Cooler Pty Limited",
    "Basic Controls",
    "GE Measurement and Control Solutions Advanced Sensors",
    "EQUAL Networks",
    "Millennial Net",
    "APLI Ltd",
    "Electro Industries/GaugeTech",
    "SangMyung University",
    "Coppertree Analytics, Inc.",
    "CoreNetiX GmbH",
    "Acutherm",
    "Dr. Riedel Automatisierungstechnik GmbH",
    "Shina System Co., Ltd",
    "Iqapertus",
    "PSE Technology",
    "BA Systems",
    "BTICINO",
    "Monico, Inc.",
    "iCue",
    "tekmar Control Systems Ltd.",
    "Control Technology Corporation",
    "GFAE GmbH",
    "BeKa Software GmbH",
    "Isoil Industria SpA",
    "Home Systems Consulting SpA",
    "Socomec",
    "Everex Communications, Inc.",
    "CET Electric Technology, Inc.",
    "Atrila GmbH",
    "WingTechs",
    "Shenzhen Mek Intellisys Pte Ltd.",
    "Nestfield Co., Ltd.",
    "Swissphone Telecom AG",
    "PNTECH JSC",
    "Horner APG, LLC",
    "PVI Industries, LLC",
    "Ela-compil",
    "Pegasus Automation International LLC",
    "Wight Electronic Services Ltd.",
    "Marcom",
    "Exhausto A/S",
    "Dwyer Instruments, Inc.",
    "Link GmbH",
    "Oppermann Regelgerate GmbH",
    "NuAire, Inc.",
    "Nortec Humidity, Inc.",
    "Bigwood Systems, Inc.",
    "Enbala Power Networks",
    "Inter Energy Co., Ltd.",
    "ETC",
    "COMELEC S.A.R.L",
    "Pythia Technologies",
    "TrendPoint Systems, Inc.",
    "AWEX",
    "Eurevia",
    "Kongsberg E-lon AS",
    "FlaktWoods",
    "E + E Elektronik GES M.B.H.",
    "ARC Informatique",
    "SKIDATA AG",
    "WSW Solutions",
    "Trefon Electronic GmbH",
    "Dongseo System",
    "Kanontec Intelligence Technology Co., Ltd.",
    "EVCO S.p.A.",
    "Accuenergy (Canada) Inc.",
    "SoftDEL",
    "Orion Energy Systems, Inc.",
    "Roboticsware",
    "DOMIQ Sp. z o.o.",
    "Solidyne",
    "Elecsys Corporation",
    "Conditionaire International Pty. Limited",
    "Quebec, Inc.",
    "Homerun Holdings",
    "Murata Americas",
    "Comptek",
    "Westco Systems, Inc.",
    "Advancis Software & Services GmbH",
    "Intergrid, LLC",
    "Markerr Controls, Inc.",
    "Toshiba Elevator and Building Systems Corporation",
    "Spectrum Controls, Inc.",
    "Mkservice",
    "Fox Thermal Instruments",
    "SyxthSense Ltd",
    "DUHA System S R.O.",
    "NIBE",
    "Melink Corporation",
    "Fritz-Haber-Institut",
    "MTU Onsite Energy GmbH, Gas Power Systems",
    "Omega Engineering, Inc.",
    "Avelon",
    "Ywire Technologies, Inc.",
    "M.R. Engineering Co., Ltd.",
    "Lochinvar, LLC",
    "Sontay Limited",
    "GRUPA Slawomir Chelminski",
    "Arch Meter Corporation",
    "Senva, Inc.",
    "Reserved for ASHRAE",
    "FM-Tec",
    "Systems Specialists, Inc.",
    "SenseAir",
    "AB IndustrieTechnik Srl",
    "Cortland Research, LLC",
    "MediaView",
    "VDA Elettronica",
    "CSS, Inc.",
    "Tek-Air Systems, Inc.",
    "ICDT",
    "The Armstrong Monitoring Corporation",
    "DIXELL S.r.l",
    "Lead System, Inc.",
    "ISM EuroCenter S.A.",
    "TDIS",
    "Trade FIDES",
    "Knürr GmbH (Emerson Network Power)",
    "Resource Data Management",
    "Abies Technology, Inc.",
    "UAB Komfovent",
    "MIRAE Electrical Mfg. Co., Ltd.",
    "HunterDouglas Architectural Projects Scandinavia ApS",
    "RUNPAQ Group Co., Ltd",
    "Unicard SA",
    "IE Technologies",
    "Ruskin Manufacturing",
    "Calon Associates Limited",
    "Contec Co., Ltd.",
    "iT GmbH",
    "Autani Corporation",
    "Christian Fortin",
    "HDL",
    "IPID Sp. Z.O.O Limited",
    "Fuji Electric Co., Ltd",
    "View, Inc.",
    "Samsung S1 Corporation",
    "New Lift",
    "VRT Systems",
    "Motion Control Engineering, Inc.",
    "Weiss Klimatechnik GmbH",
    "Elkon",
    "Eliwell Controls S.r.l.",
    "Japan Computer Technos Corp",
    "Rational Network ehf",
    "Magnum Energy Solutions, LLC",
    "MelRok",
    "VAE Group",
    "LGCNS",
    "Berghof Automationstechnik GmbH",
    "Quark Communications, Inc.",
    "Sontex",
    "mivune AG",
    "Panduit",
    "Smart Controls, LLC",
    "Compu-Aire, Inc.",
    "Sierra",
    "ProtoSense Technologies",
    "Eltrac Technologies Pvt Ltd",
    "Bektas Invisible Controls GmbH",
    "Entelec",
    "INNEXIV",
    "Covenant",
    "Davitor AB",
    "TongFang Technovator",
    "Building Robotics, Inc.",
    "HSS-MSR UG",
    "FramTack LLC",
    "B. L. Acoustics, Ltd.",
    "Traxxon Rock Drills, Ltd",
    "Franke",
    "Wurm GmbH & Co",
    "AddENERGIE",
    "Mirle Automation Corporation",
    "Ibis Networks",
    "ID-KARTA s.r.o.",
    "Anaren, Inc.",
    "Span, Incorporated",
    "Bosch Thermotechnology Corp",
    "DRC Technology S.A.",
    "Shanghai Energy Building Technology Co, Ltd",
    "Fraport AG",
    "Flowgroup",
    "Skytron Energy, GmbH",
    "ALTEL Wicha, Golda Sp. J.",
    "Drupal",
    "Axiomatic Technology, Ltd",
    "Bohnke + Partner",
    "Function1",
    "Optergy Pty, Ltd",
    "LSI Virticus",
    "Konzeptpark GmbH",
    "NX Lighting Controls",
    "eCurv, Inc.",
    "Agnosys GmbH",
    "Shanghai Sunfull Automation Co., LTD",
    "Kurz Instruments, Inc.",
    "Cias Elettronica S.r.l.",
    "Multiaqua, Inc.",
    "BlueBox",
    "Sensidyne",
    "Viessmann Elektronik GmbH",
    "ADFweb.com srl",
    "Gaylord Industries",
    "Majur Ltd.",
    "Shanghai Huilin Technology Co., Ltd.",
    "Exotronic",
    "SAFECONTROL s.r.o.",
    "Amatis",
    "Universal Electric Corporation",
    "iBACnet",
    "Reserved for ASHRAE",
    "Smartrise Engineering, Inc.",
    "Miratron, Inc.",
    "SmartEdge",
    "Mitsubishi Electric Australia Pty Ltd",
    "Triangle Research International Ptd Ltd",
    "Produal Oy",
    "Milestone Systems A/S",
    "Trustbridge",
    "Feedback Solutions",
    "IES",
    "ABB Power Protection SA",
    "Riptide IO",
    "Messerschmitt Systems AG",
    "Dezem Energy Controlling",
    "MechoSystems",
    "evon GmbH",
    "CS Lab GmbH",
    "8760 Enterprises, Inc.",
    "Touche Controls",
    "Ontrol Teknik Malzeme San. ve Tic. A.S.",
    "Uni Control System Sp. Z o.o.",
    "Weihai Ploumeter Co., Ltd",
    "Elcom International Pvt. Ltd",
    "Signify",
    "AutomationDirect",
    "Paragon Robotics",
    "SMT System & Modules Technology AG",
    "Radix IoT LLC",
    "CMR Controls Ltd",
    "Innovari, Inc.",
    "ABB Control Products",
    "Gesellschaft fur Gebäudeautomation mbH",
    "RODI Systems Corp.",
    "Nextek Power Systems",
    "Creative Lighting",
    "WaterFurnace International",
    "Mercury Security",
    "Hisense (Shandong) Air-Conditioning Co., Ltd.",
    "Layered Solutions, Inc.",
    "Leegood Automatic System, Inc.",
    "Shanghai Restar Technology Co., Ltd.",
    "Reimann Ingenieurbüro",
    "LynTec",
    "HTP",
    "Elkor Technologies, Inc.",
    "Bentrol Pty Ltd",
    "Team-Control Oy",
    "NextDevice, LLC",
    "iSMA CONTROLLI S.p.a.",
    "King I Electronics Co., Ltd",
    "SAMDAV",
    "Next Gen Industries Pvt. Ltd.",
    "Entic LLC",
    "ETAP",
    "Moralle Electronics Limited",
    "Leicom AG",
    "Watts Regulator Company",
    "S.C. Orbtronics S.R.L.",
    "Gaussan Technologies",
    "WEBfactory GmbH",
    "Ocean Controls",
    "Messana Air-Ray Conditioning s.r.l.",
    "Hangzhou BATOWN Technology Co. Ltd.",
    "Reasonable Controls",
    "Servisys, Inc.",
    "halstrup-walcher GmbH",
    "SWG Automation Fuzhou Limited",
    "KSB Aktiengesellschaft",
    "Hybryd Sp. z o.o.",
    "Helvatron AG",
    "Oderon Sp. Z.O.O.",
    "mikolab",
    "Exodraft",
    "Hochhuth GmbH",
    "Integrated System Technologies Ltd.",
    "Shanghai Cellcons Controls Co., Ltd",
    "Emme Controls, LLC",
    "Field Diagnostic Services, Inc.",
    "Ges Teknik A.S.",
    "Global Power Products, Inc.",
    "Option NV",
    "BV-Control AG",
    "Sigren Engineering AG",
    "Shanghai Jaltone Technology Co., Ltd.",
    "MaxLine Solutions Ltd",
    "Kron Instrumentos Elétricos Ltda",
    "Thermo Matrix",
    "Infinite Automation Systems, Inc.",
    "Vantage",
    "Elecon Measurements Pvt Ltd",
    "TBA",
    "Carnes Company",
    "Harman Professional",
    "Nenutec Asia Pacific Pte Ltd",
    "Gia NV",
    "Kepware Tehnologies",
    "Temperature Electronics Ltd",
    "Packet Power",
    "Project Haystack Corporation",
    "DEOS Controls Americas Inc.",
    "Senseware Inc",
    "MST Systemtechnik AG",
    "Lonix Ltd",
    "Gossen Metrawatt GmbH",
    "Aviosys International Inc.",
    "Efficient Building Automation Corp.",
    "Accutron Instruments Inc.",
    "Vermont Energy Control Systems LLC",
    "DCC Dynamics",
    "B.E.G. Brück Electronic GmbH",
    "Reserved for ASHRAE",
    "NGBS Hungary Ltd.",
    "ILLUM Technology, LLC",
    "Delta Controls Germany Limited",
    "S+T Service & Technique S.A.",
    "SimpleSoft",
    "Altair Engineering",
    "EZEN Solution Inc.",
    "Fujitec Co. Ltd.",
    "Terralux",
    "Annicom",
    "Bihl+Wiedemann GmbH",
    "Draper, Inc.",
    "Schüco International KG",
    "Otis Elevator Company",
    "Fidelix Oy",
    "RAM GmbH Mess- und Regeltechnik",
    "WEMS",
    "Ravel Electronics Pvt Ltd",
    "OmniMagni",
    "Echelon",
    "Intellimeter Canada, Inc.",
    "Bithouse Oy",
    "Reserved for ASHRAE",
    "BuildPulse",
    "Shenzhen 1000 Building Automation Co. Ltd",
    "AED Engineering GmbH",
    "Güntner GmbH & Co. KG",
    "KNXlogic",
    "CIM Environmental Group",
    "Flow Control",
    "Lumen Cache, Inc.",
    "Ecosystem",
    "Potter Electric Signal Company, LLC",
    "Tyco Fire & Security S.p.A.",
    "Watanabe Electric Industry Co., Ltd.",
    "Causam Energy",
    "W-tec AG",
    "IMI Hydronic Engineering International SA",
    "ARIGO Software",
    "MSA Safety",
    "Smart Solucoes Ltda – MERCATO",
    "PIATRA Engineering",
    "ODIN Automation Systems, LLC",
    "Belparts NV",
    "UAB, SALDA",
    "Alre-IT Regeltechnik GmbH",
    "Ingenieurbüro H. Lertes GmbH & Co. KG",
    "Breathing Buildings",
    "eWON SA",
    "Cav. Uff. Giacomo Cimberio S.p.A",
    "PKE Electronics AG",
    "Allen",
    "Kastle Systems",
    "Logical Electro-Mechanical (EM) Systems, Inc.",
    "ppKinetics Instruments, LLC",
    "Cathexis Technologies",
    "Sylop sp. Z o.o. sp.k",
    "Brauns Control GmbH",
    "OMRON SOCIAL SOLUTIONS CO., LTD.",
    "Wildeboer Bauteile Gmbh",
    "Shanghai Biens Technologies Ltd",
    "Beijing HZHY Technology Co., Ltd",
    "Building Clouds",
    "The University of Sheffield-Department of Electronic and Electrical Engineering",
    "Fabtronics Australia Pty Ltd",
    "SLAT",
    "Software Motor Corporation",
    "Armstrong International Inc.",
    "Steril-Aire, Inc.",
    "Infinique",
    "Arcom",
    "Argo Performance, Ltd",
    "Dialight",
    "Ideal Technical Solutions",
    "Neurobat AG",
    "Neyer Software Consulting LLC",
    "SCADA Technology Development Co., Ltd.",
    "Demand Logic Limited",
    "GWA Group Limited",
    "Occitaline",
    "NAO Digital Co., Ltd.",
    "Shenzhen Chanslink Network Technology Co., Ltd.",
    "Samsung Electronics Co., Ltd.",
    "Mesa Laboratories, Inc.",
    "Fischer",
    "OpSys Solutions Ltd.",
    "Advanced Devices Limited",
    "Condair",
    "INELCOM Ingenieria Electronica Comercial S.A.",
    "GridPoint, Inc.",
    "ADF Technologies Sdn Bhd",
    "EPM, Inc.",
    "Lighting Controls Ltd",
    "Perix Controls Ltd.",
    "AERCO International, Inc.",
    "KONE Inc.",
    "Ziehl-Abegg SE",
    "Robot, S.A.",
    "Optigo Networks, Inc.",
    "Openmotics BVBA",
    "Metropolitan Industries, Inc.",
    "Huawei Technologies Co., Ltd.",
    "Digital Lumens, Inc.",
    "Vanti",
    "Cree Lighting",
    "Richmond Heights SDN BHD",
    "Payne-Sparkman Lighting Mangement",
    "Ashcroft",
    "Jet Controls Corp",
    "Zumtobel Lighting GmbH",
    "Reserved for ASHRAE",
    "Ekon GmbH",
    "Molex",
    "Maco Lighting Pty Ltd.",
    "Axecon Corp.",
    "Tensor plc",
    "Kaseman Environmental Control Equipment (Shanghai) Limited",
    "AB Axis Industries",
    "Netix Controls",
    "Eldridge Products, Inc.",
    "Micronics",
    "Fortecho Solutions Ltd",
    "Sellers Manufacturing Company",
    "Rite-Hite Doors, Inc.",
    "Violet Defense LLC",
    "Simna",
    "Multi-Énergie Best Inc.",
    "Mega System Technologies, Inc.",
    "Rheem",
    "Ing. Punzenberger COPA-DATA GmbH",
    "MEC Electronics GmbH",
    "Taco Comfort Solutions",
    "Alexander Maier GmbH",
    "Ecorithm, Inc.",
    "Accurro Ltd",
    "ROMTECK Australia Pty Ltd",
    "Splash Monitoring Limited",
    "Light Application",
    "Logical Building Automation",
    "Exilight Oy",
    "Hager Electro SAS",
    "KLIF Co., LTD",
    "HygroMatik",
    "Daniel Mousseau Programmation & Electronique",
    "Aerionics Inc.",
    "M2S Electronique Ltee",
    "Automation Components, Inc.",
    "Niobrara Research & Development Corporation",
    "Netcom Sicherheitstechnik GmbH",
    "Lumel S.A.",
    "Great Plains Industries, Inc.",
    "Domotica Labs S.R.L",
    "Energy Cloud, Inc.",
    "Vomatec",
    "Demma Companies",
    "Valsena",
    "Comsys Bärtsch AG",
    "bGrid",
    "MDJ Software Pty Ltd",
    "Dimonoff, Inc.",
    "Edomo Systems, GmbH",
    "Effektiv, LLC",
    "SteamOVap",
    "grandcentrix GmbH",
    "Weintek Labs, Inc.",
    "Intefox GmbH",
    "Radius22 Automation Company",
    "Ringdale, Inc.",
    "Iwaki America",
    "Bractlet",
    "STULZ Air Technology Systems, Inc.",
    "Climate Ready Engineering Pty Ltd",
    "Genea Energy Partners",
    "IoTall Chile",
    "IKS Co., Ltd.",
    "Yodiwo AB",
    "TITAN electronic GmbH",
    "IDEC Corporation",
    "SIFRI SL",
    "Thermal Gas Systems Inc.",
    "Building Automation Products, Inc.",
    "Asset Mapping",
    "Smarteh Company",
    "Datapod (Australia) Pty Ltd.",
    "Buildings Alive Pty Ltd",
    "Digital Elektronik",
    "Talent Automação e Tecnologia Ltda",
    "Norposh Limited",
    "Merkur Funksysteme AG",
    "Faster CZ spol. S.r.o",
    "Eco-Adapt",
    "Energocentrum Plus, s.r.o",
    "amBX UK Ltd",
    "Western Reserve Controls, Inc.",
    "LayerZero Power Systems, Inc.",
    "CIC Jan Hřebec s.r.o.",
    "Sigrov BV",
    "ISYS-Intelligent Systems",
    "Gas Detection (Australia) Pty Ltd",
    "Kinco Automation (Shanghai) Ltd.",
    "Lars Energy, LLC",
    "Flamefast (UK) Ltd.",
    "Royal Service Air Conditioning",
    "Ampio Sp. Z o.o.",
    "Inovonics Wireless Corporation",
    "Nvent Thermal Management",
    "Sinowell Control System Ltd",
    "Moxa Inc.",
    "Matrix iControl SDN BHD",
    "PurpleSwift",
    "OTIM Technologies",
    "FlowMate Limited",
    "Degree Controls, Inc.",
    "Fei Xing (Shanghai) Software Technologies Co., Ltd.",
    "Berg GmbH",
    "ARENZ.IT",
    "Edelstrom Electronic Devices & Designing LLC",
    "Drive Connect, LLC",
    "DevelopNow",
    "Poort",
    "VMEIL Information (Shanghai) Ltd",
    "Rayleigh Instruments",
    "Reserved for ASHRAE",
    "CODESYS Development",
    "Smartware Technologies Group, LLC",
    "Polar Bear Solutions",
    "Codra",
    "Pharos Architectural Controls Ltd",
    "EngiNear Ltd.",
    "Ad Hoc Electronics",
    "Unified Microsystems",
    "Industrieelektronik Brandenburg GmbH",
    "Hartmann GmbH",
    "Piscada",
    "KMB systems, s.r.o.",
    "PowerTech Engineering AS",
    "Telefonbau Arthur Schwabe GmbH & Co. KG",
    "Wuxi Fistwelove Technology Co., Ltd.",
    "Prysm",
    "STEINEL GmbH",
    "Georg Fischer JRG AG",
    "Make Develop SL",
    "Monnit Corporation",
    "Mirror Life Corporation",
    "Secure Meters Limited",
    "PECO",
    ".CCTECH, Inc.",
    "LightFi Limited",
    "Nice Spa",
    "Fiber SenSys, Inc.",
    "B&D Buchta und Degeorgi",
    "Ventacity Systems, Inc.",
    "Hitachi-Johnson Controls Air Conditioning, Inc.",
    "Sage Metering, Inc.",
    "Andel Limited",
    "ECOSmart Technologies",
    "S.E.T.",
    "Protec Fire Detection Spain SL",
    "AGRAMER UG",
    "Anylink Electronic GmbH",
    "Schindler, Ltd",
    "Jibreel Abdeen Est.",
    "Fluidyne Control Systems Pvt. Ltd",
    "Prism Systems, Inc.",
    "Enertiv",
    "Mirasoft GmbH & Co. KG",
    "DUALTECH IT",
    "Countlogic, LLC",
    "Kohler",
    "Chen Sen Controls Co., Ltd.",
    "Greenheck",
    "Intwine Connect, LLC",
    "Karlborgs Elkontroll",
    "Datakom",
    "Hoga Control AS",
    "Cool Automation",
    "Inter Search Co., Ltd",
    "DABBEL-Automation Intelligence GmbH",
    "Gadgeon Engineering Smartness",
    "Coster Group S.r.l.",
    "Walter Müller AG",
    "Fluke",
    "Quintex Systems Ltd",
    "Senfficient SDN BHD",
    "Nube iO Operations Pty Ltd",
    "DAS Integrator Pte Ltd",
    "CREVIS Co., Ltd",
    "iSquared software inc.",
    "KTG GmbH",
    "POK Group Oy",
    "Adiscom",
    "Incusense",
    "75F",
    "Anord Mardix, Inc.",
    "HOSCH Gebäudeautomation Neue Produkte GmbH",
    "Bosch.IO GmbH",
    "Royal Boon Edam International B.V.",
    "Clack Corporation",
    "Unitex Controls LLC",
    "KTC Göteborg AB",
    "Interzon AB",
    "ISDE ING SL",
    "ABM automation building messaging GmbH",
    "Kentec Electronics Ltd",
    "Emerson Commercial and Residential Solutions",
    "Powerside",
    "SMC Group",
    "EOS Weather Instruments",
    "Zonex Systems",
    "Generex Systems Computervertriebsgesellschaft mbH",
    "Energy Wall LLC",
    "Thermofin",
    "SDATAWAY SA",
    "Biddle Air Systems Limited",
    "Kessler Ellis Products",
    "Thermoscreens",
    "Modio",
    "Newron Solutions",
    "Unitronics",
    "TRILUX GmbH & Co. KG",
    "Kollmorgen Steuerungstechnik GmbH",
    "Bosch Rexroth AG",
    "Alarko Carrier",
    "Verdigris Technologies",
    "Shanghai SIIC-Longchuang Smartech So., Ltd.",
    "Quinda Co.",
    "GRUNER AG",
    "BACMOVE",
    "PSIDAC AB",
    "ISICON-Control Automation",
    "Big Ass Fans",
    "din – Dietmar Nocker Facility Management GmbH",
    "Teldio",
    "MIKROKLIMA s.r.o.",
    "Density",
    "ICONAG-Leittechnik GmbH",
    "Awair",
    "T&D Engineering, Ltd",
    "Sistemas Digitales",
    "Loxone Electronics GmbH",
    "ActronAir",
    "Inductive Automation",
    "Thor Engineering GmbH",
    "Berner International, LLC",
    "Potsdam Sensors LLC",
    "Kohler Mira Ltd",
    "Tecomon GmbH",
    "Two Dimensional Instruments, LLC",
    "LEFA Technologies Pte. Ltd.",
    "EATON CEAG Notlichtsysteme GmbH",
    "Commbox Tecnologia",
    "IPVideo Corporation",
    "Bender GmbH & Co. KG",
    "Rhymebus Corporation",
    "Axon Systems Ltd",
    "Engineered Air",
    "Elipse Software Ltda",
    "Simatix Building Technologies Pvt. Ltd.",
    "W.A. Benjamin Electric Co.",
    "TROX Air Conditioning Components (Suzhou) Co. Ltd.",
    "SC Medical Pty Ltd.",
    "Elcanic A/S",
    "Obeo AS",
    "Tapa, Inc.",
    "ASE Smart Energy, Inc.",
    "Performance Services, Inc.",
    "Veridify Security",
    "CD Innovation LTD",
    "Ben Peoples Industries, LLC",
    "UNICOMM Sp. z o.o",
    "Thing Technologies GmbH",
    "Beijing Hailin Control Technology, Inc.",
    "Digital Realty",
    "Agrowtek Inc.",
    "DSP Innovation BV",
    "STV Electronic GmbH",
    "Elmeasure India Pvt Ltd.",
    "Pineshore Energy LLC",
    "Brasch Environmental Technologies, LLC",
    "Lion Controls Co., LTD",
    "Sinux",
    "Avnet Inc.",
    "Somfy Activites SA",
    "Amico",
    "SageGlass",
    "AuVerte",
    "Agile Connects Pvt. Ltd.",
    "Locimation Pty Ltd",
    "Envio Systems GmbH",
    "Voytech Systems Limited",
    "Davidsmeyer und Paul GmbH",
    "Lusher Engineering Services",
    "CHNT Nanjing Techsel Intelligent Company LTD",
    "Threetronics Pty Ltd",
    "SkyFoundry, LLC",
    "HanilProTech",
    "Sensorscall",
    "Shanghai Jingpu Information Technology, Co., Ltd.",
    "Lichtmanufaktur Berlin GmbH",
    "Eco Parking Technologies",
    "Envision Digital International Pte Ltd",
    "Antony Developpement Electronique",
    "i2systems",
    "Thureon International Limited",
    "Pulsafeeder",
    "MegaChips Corporation",
    "TES Controls",
    "Cermate",
    "Grand Valley State University",
    "Symcon Gmbh",
    "The Chicago Faucet Company",
    "Geberit AG",
    "Rex Controls",
    "IVMS GmbH",
    "MNPP Saturn Ltd.",
    "Regal Beloit",
    "ACS-Air Conditioning Solutions",
    "GBX Technology, LLC",
    "Kaiterra",
    "ThinKuan loT Technology (Shanghai) Co., Ltd",
    "HoCoSto B.V.",
    "Shenzhen AS-AI Technology Co., Ltd.",
    "RPS S.p.a.",
    "Esmé solutions",
    "IOTech Systems Limited",
    "i-AutoLogic Co., Ltd.",
    "New Age Micro, LLC",
    "Guardian Glass",
    "Guangzhou Zhaoyu Information Technology",
    "ACE IoT Solutions LLC",
    "Poris Electronics Co., Ltd.",
    "Terminus Technologies Group",
    "Intech 21, Inc.",
    "Accurate Electronics",
    "Fluence Bioengineering",
    "Mun Hean Singapore Pte Ltd",
    "Katronic AG & Co. KG",
    "Suzhou XinAo Information Technology Co. Ltd",
    "Linktekk Technology, JSC.",
    "Stirling Ultracold",
    "UV Partners, Inc.",
    "ProMinent GmbH",
    "Multi-Tech Systems, Inc.",
    "JUMO GmbH & Co. KG",
    "Qingdao Huarui Technology Co. Ltd.,",
    "Cairn Systemes",
    "NeuroLogic Research Corp.",
    "Transition Technologies Advanced Solutions Sp. z o.o",
    "Xxter bv",
    "PassiveLogic",
    "EnSmart Controls",
    "Watts Heating and Hot Water Solutions, dba Lync",
    "Troposphaira Technologies LLP",
    "Network Thermostat",
    "Titanium Intelligent Solutions, LLC",
    "Numa Products, LLC",
    "WAREMA Renkhoff SE",
    "Frese A/S",
    "Mapped",
    "ELEKTRODESIGN ventilatory s.r.o",
    "AirCare Automation, Inc.",
    "Antrum",
    "Bao Linh Connect Technology",
    "Virginia Controls, LLC",
    "Duosys SDN BHD",
    "Onsen SAS",
    "Vaughn Thermal Corporation",
    "Thermoplastic Engineering Ltd (TPE)",
    "Wirth Research Ltd.",
    "SST Automation",
    "Shanghai Bencol Electronic Technology Co., Ltd",
    "AIWAA Systems Private Limited",
    "Enless Wireless",
    "Ozuno Engineering Pty Ltd",
    "Hubbell, The Electric Heater Company",
    "Industrial Turnaround Corporation (ITAC)",
    "Wadsworth Control Systems",
    "Services Hilo Inc.",
    "iDM Energiesysteme GmbH",
    "BeNext B.V.",
    "CleanAir.ai Corporation",
    "Revolution Microelectronics (America) Inc.",
    "Real-Time Systems GmbH",
    "ZedBee Technologies Pvt Ltd",
    "Winmate Technology Solutions Pvt. Ltd.",
    "Senticon Ltd.",
    "Rossaker AB",
    "OPIT Solutions Ltd",
    "Hotowell International Co., Limited",
    "Inim Electronics S.R.L. Unipersonale",
    "Airthings ASA",
    "Analog Devices, Inc.",
    "AIDirections DMCC",
    "Prima Electro S.p.A.",
    "KLT Control System Ltd.",
    "Evolution Controls Inc.",
    "Bever Innovations",
    "Pelican Wireless Systems",
    "Control Concepts Inc.",
    "Augmatic Technologies Pvt. Ltd.",
    "Xiamen Milesight loT Co., Ltd",
    "Tianjin Anjie loT Schience and Technology Co., Ltd",
    "Guangzhou S. Energy Electronics Technology Co. Ltd.",
    "AKVO Atmospheric Water Systems Pvt. Ltd.",
    "EmFirst Co. Ltd.",
    "Iion Systems ApS",
    "UNKNOWN",
    "SAF Tehnika JSC",
    "Komfort IQ, Inc.",
    "CoolTera Limited",
    "Hadron Solutions S.r.l.s",
    "UNKNOWN",
    "Bitpool",
    "Sonicu, LLC",
    "Rishabh Instruments Limited",
    "Thing Warehouse LLC",
    "Innofriends GmbH",
    "Metronic AKP Sp. J.",
    "Techknave",
    "Elsner Elektronik",
    "LEFOO Industrial (Hangzhou) Co., Ltd.",
    "Calibration Technologies, Inc.",
    "Allorado",
    "Verkada",
    "Wattsense",
    "Emerson Automation Solutions",
    "Growlink",
    "Olympia Electronics",
    "Normal Software, Inc.",
    "ST Engineering Solution JSC",
    "Industrial Flow Solutions",
    "Ubiqisense ApS",
    "Tiger-Soft",
    "Ecodom Srl",
    "Bilgipro IoT Systems",
    "planspur netdesign GmbH",
    "Dolphin Solutions Ltd",
    "Mitsubishi Electric Corporation, Kobe Works",
    "Ecovena",
    "Gree Electric Appliances Inc of Zhuhai",
    "Conspec Controls",
    "Hangzhou Hikvision Digital Technology Co., Ltd.",
    "Crystal Peak Security",
    "PermAlert",
    "Zhejiang Misilin Technology Co., Ltd.",
    "Dekker Vacuum Technologies",
    "Edwards Limited",
    "Leybold GmbH",
    "International Gas Detectors",
    "Atlas Copco Airpower NV",
    "Air Sentry Limited",
    "Aelsys",
    "Granby Consulting LLC",
    "Clever Relay",
    "Monico Monitoring, Inc.",
    "Oqdo",
    "Matrix Comsec Private Limited",
    "Resource Solutions",
    "American Gas Safety, LLC",
    "S&S Northern Ltd.",
    "Ulbios Techsens",
    "Bowery Farming, Inc.",
    "Ryobi Limited",
    "EkkoSense Ltd",
    "ClimaCool",
    "Grid Connect Inc.",
    "Ziegler Instrumentation UK Ltd",
    "ControlTec, LLC",
    "Aeterlink Corporation",
    "Alpha Epsilon Automation",
    "Astralite Inc.",
    "Delta Fire Ltda.",
    "Bock Water Heaters, Inc.",
    "Cleaver-Brooks",
    "Scanalytics, Inc.",
    "WI6LABS",
    "AC&T System Co., Ltd",
    "VergeSense",
    "Systemair Mfg. Inc.",
    "Seeley International",
    "Crane Building Services & Utilities",
    "Brady Corporation",
    "Qingdao Hisense Hitachi Air-Conditioning Systems Co., Ltd.",
    "Golden Quality Co. Ltd.",
    "Elvaco AB",
    "Strong Technology, LLC",
    "REC Environmental Technology (Guangzhou) Company Limited",
    "Disruptive Technologies Research AS",
    "Nico Consultancy Limited",
    "Horten lot (Jiangsu) Co., Ltd.",
    "Paxton Controls Corp.",
    "Fell Technology AS",
    "SHLOK Information Systems India Private Limited",
    "Microgro PLC Ltd.",
    "Clouder Oy",
    "Gebäude Automatisierung GmbH",
    "solvimus GmbH"
  };
}